HMS.Web/Controllers/AccomodationDetailsController.cs
using HMS.Services;
using HMS.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace HMS.Web.Controllers
{
    public class AccomodationDetailsController : Controller
    {
        private AccomodationTypeService _AccomodationTypeService;
        private AccomodationPackagesService _AccomodationPackagesService;
        private AccomodationService _AccomodationService;
        private AccomodationDitailsViewModel _model;
        public AccomodationDetailsController()
        {
            _AccomodationTypeService = new AccomodationTypeService();
            _AccomodationPackagesService = new AccomodationPackagesService();
            _AccomodationService = new AccomodationService();
            _AccomodationTypeService = new AccomodationTypeService();
            _model = new AccomodationDitailsViewModel();
        }
        // GET: AccomodationDetails
        public  ActionResult Index(int accomodationTypeID, int? accomodationPackageID)
        {
            _model.AccomodationPackages =  _AccomodationPackagesService.GetAccomodationPackageByAccomodationTypeId(accomodationTypeID);
            _model.SelctedAccomodationPackageID = accomodationPackageID.HasValue? accomodationPackageID.Value:_model.AccomodationPackages.FirstOrDefault().ID;
            _model.Accomodations = _AccomodationService.GetAccomodationByAccomodationPackageId(_model.SelctedAccomodationPackageID);
            _model.AccomodationTypeId = accomodationTypeID;
            return View(_model);
        }
    }
}

HMS.Web/Views/AccomodationDetails/Index.cshtml
@model HMS.Web.ViewModels.AccomodationDitailsViewModel
<aside id="colorlib-hero">
    <div class="flexslider">
        <ul class="slides">
            <li style="background-image: url(/Content/images/img_bg_5.jpg);">
                <div class="overlay"></div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-md-offset-3 slider-text">
                            <div class="slider-text-inner slider-text-inner2 text-center">
                                <h2>Choose our Best</h2>
                                <h1>Rooms &amp; Suites</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</aside>
@if (Model != null && Model.AccomodationPackages != null && Model.AccomodationPackages.Count > 0)
{
<div id="colorlib-rooms" class="colorlib-light-grey">
    <div class="container">
        <div class="row">
            <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Select Accomodation Package
                </button>
                <ul class="dropdown-menu">
                @foreach (var data in Model.AccomodationPackages)
                {
                    <li class="@(data.ID == Model.SelctedAccomodationPackageID?"active":string.Empty )">
                        <a href="@Url.Action("Index","AccomodationDetails",new { accomodationTypeID = Model.AccomodationTypeId, accomodationPackageID=data.ID })">@data.Name</a>
                    </li>
                }
                </ul>
                

            </div>
            @if (Model.Accomodations != null & Model.Accomodations.Count > 0)
            {
                foreach (var accomodation in Model.Accomodations)
                {
                <div class="col-md-4 room-wrap animate-box">
                    <a href="/Content/images/room-1.jpg" class="room image-popup-link" style="background-image: url(/Content/images/room-1.jpg);"></a>
                    <div class="desc text-center">
                        <span class="rate-star"><i class="icon-star-full full"></i><i class="icon-star-full full"></i><i class="icon-star-full full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span>
                        <h3><a href="rooms-suites.html">@accomodation.Name</a></h3>
                        <p class="price">
                            <span class="currency">$</span>
                            <span class="price-room">@accomodation.AccomodationPackage.FeePerNight</span>
                            <span class="per">/ per night</span>
                        </p>
                        <ul>
                            <li>No of rooms : @accomodation.AccomodationPackage.NoOfRoom</li>
                        </ul>
                        <p><a class="btn btn-primary">Book now!</a></p>
                    </div>
                </div>
                }
            }
            else
            {
                <div class="alert alert-warning">
                    No Accomodation found. 
                </div>
            }

        </div>
    </div>
</div>
}