HMS.Web/Areas/Dashboard/Controllers/AccomodationPackagesController.cs
using HMS.Entities;
using HMS.Services;
using HMS.Web.Areas.Dashboard.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HMS.Web.Areas.Dashboard.Controllers
{
    public class AccomodationPackagesController : Controller
    {
        private AccomodationPackagesService _AccomodationPackagesService;
        private AccomodationPackage _AccomodationPackage;
        private AccomodationTypeService _AccomodationTypeService;
        private SharedService _SharedService;
        private Picture _Picture;
        public AccomodationPackagesController()
        {
            _AccomodationPackagesService = new AccomodationPackagesService();
            _AccomodationPackage = new AccomodationPackage();
            _AccomodationTypeService = new AccomodationTypeService();
            _Picture = new Picture();
            _SharedService = new SharedService();
        }
        // GET: Dashboard/AccomodationType
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult Listing(string searchTearm, int? pageNo, int? pageSize)
        {
            AccomodationPackagesListingModel model = new AccomodationPackagesListingModel();
            pageNo = pageNo ?? 1;
            pageSize = pageSize ?? 10;
            model.AccomodationPackages = _AccomodationPackagesService.GetAllAccomodationPackage(searchTearm, pageNo.Value, pageSize.Value);
            int totalItems = _AccomodationPackagesService.TotalItemCount(searchTearm);
            model.Pager = new Pager(totalItems, pageNo, pageSize.Value);
            model.SearchTerm = searchTearm;
            model.PageNo = pageNo.Value;
            model.PageSize = pageSize.Value;
            return PartialView("_Listing", model);
        }
        [HttpGet]
        public PartialViewResult Action(int? id)
        {
            AccomodationPackagesModel model = new AccomodationPackagesModel();
            if (id.HasValue)
            {
                _AccomodationPackage = _AccomodationPackagesService.GetAccomodationPackagesById(id.Value);
                model.ID = _AccomodationPackage.ID;
                model.Name = _AccomodationPackage.Name;
                model.NoOfRoom = _AccomodationPackage.NoOfRoom;
                model.AccomodationTypeID = _AccomodationPackage.AccomodationTypeID;
                model.FeePerNight = _AccomodationPackage.FeePerNight;
                model.AccomodationPackagePictures = _AccomodationPackage.AccomodationPackagePictures;
            }
                model.AccomodationType = _AccomodationTypeService.GetAllAccomodationType();

            return PartialView("_Action", model);
        }
        [HttpPost]
        public JsonResult Action(AccomodationPackagesModel model)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            var message = "";
            bool data = false;
            try
            {
                if (ModelState.IsValid)
                {
                    List<int> picturesIDs = model.PictureIDs.Split(',').Select(x => int.Parse(x)).ToList();
                    var pictures = _SharedService.GetPicturesByIDs(picturesIDs);
                
                    if (model.ID > 0)
                    {

                        _AccomodationPackage = _AccomodationPackagesService.GetAccomodationPackagesById(model.ID);
                        _AccomodationPackage.NoOfRoom = model.NoOfRoom;
                        _AccomodationPackage.Name = model.Name;
                        _AccomodationPackage.FeePerNight = model.FeePerNight;
                        _AccomodationPackage.AccomodationTypeID = model.AccomodationTypeID;
                        _AccomodationPackage.AccomodationPackagePictures.Clear();
                        _AccomodationPackage.AccomodationPackagePictures.AddRange(pictures.Select(x => new AccomodationPackagePictures() { PictuerID = x.ID, AccomodationPackageID = model.ID }));
                        data = _AccomodationPackagesService.UpdateAccomodationPackages(_AccomodationPackage);
                    }
                    else
                    {
                        _AccomodationPackage.AccomodationPackagePictures = new List<AccomodationPackagePictures>();
                        _AccomodationPackage.AccomodationPackagePictures.AddRange(pictures.Select(x => new AccomodationPackagePictures() { PictuerID = x.ID }));
                        _AccomodationPackage.ID = model.ID;
                        _AccomodationPackage.Name = model.Name;
                        _AccomodationPackage.NoOfRoom = model.NoOfRoom;
                        _AccomodationPackage.FeePerNight = model.FeePerNight;
                        _AccomodationPackage.AccomodationTypeID = model.AccomodationTypeID;
                        data = _AccomodationPackagesService.SaveAccomodationPackages(_AccomodationPackage);
                    }

                }
                else
                {
                    message = "Please enter valid data!!";

                }

            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            if (data)
            {
                message = "Data Save Successfully!!";
                result.Data = new { Success = true, Message = message };
            }
            else
            {
                result.Data = new { Success = false, Message = message };
            }
            return result;

        }

        public JsonResult Delete(int id)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            dynamic message = "";
            var data = false;
            try
            {
                if (id > 0)
                {
                    _AccomodationPackage = _AccomodationPackagesService.GetAccomodationPackagesById(id);
                    data = _AccomodationPackagesService.DeleteAccomodationPackages(_AccomodationPackage);
                }
                else
                {
                    message = "Please click valid item";
                }
            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            if (data)
            {
                message = "Data Delete Successfully !!";
                result.Data = new { Success = true, Message = message };
            }
            else
            {
                result.Data = new { Success = false, Message = message };
            }

            return result;
        } 


    }
}

HMS.Web/Areas/Dashboard/Controllers/SharedController.cs
using HMS.Entities;
using HMS.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HMS.Web.Areas.Dashboard.Controllers
{
    public class SharedController : Controller
    {
        private SharedService _SharedService;

        public SharedController()
        {
            _SharedService = new SharedService();

        }
        // GET: Dashboard/Shared
        public ActionResult Index()
        {
            return View();
        }

     


        
        public JsonResult UploadPicture()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            var files = Request.Files;
            List<object> pictuerJSON = new List<object>();
            try
            {
                for (int i = 0; i < files.Count; i++)
                {
                    var picture = files[i];
                    var fileName = Guid.NewGuid() + Path.GetExtension(picture.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/images/AccomodationPackage/"), fileName);
                    picture.SaveAs(path);
                    var dbPictuer = new Picture();
                    dbPictuer.URL = fileName;
                    int pictureID = _SharedService.SavePicture(dbPictuer);
                    pictuerJSON.Add(new { ID = pictureID, URL = dbPictuer.URL });

                }
                result.Data = new { Success = true, pictuerJSON };
            }
            
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }
            return result;
        }
    }
}

HMS.Web/Areas/Dashboard/Views/AccomodationPackages/Index.cshtml
<div id="listData">
    @{Html.RenderAction("Listing");}
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
    </div>
</div>

HMS.Web/Areas/Dashboard/Views/AccomodationPackages/_Action.cshtml
@model HMS.Web.Areas.Dashboard.ViewModels.AccomodationPackagesModel
@if (Model != null)
{
    <div class="modal-content">
        <div class="modal-header  bg-gradient-gray-dark">
            @if (Model.ID > 0)
                {
                <h5 class="modal-title" id="exampleModalLabel">Edit Accomodation Package </h5>
            }
            else
            {
                <h5 class="modal-title" id="exampleModalLabel">Create Accomodation Package </h5>
            }

            <button type="button" class="close btn btn-warning btn-sm" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="accomodationPacakgeForm">
                <div class="form-group">
                    <label for="Name">Name</label>
                    <select name="AccomodationTypeID" class="form-control select2 select2-danger" data-dropdown-css-class="select2-danger" style="width: 100%;">

                        @if (Model.AccomodationTypeID <= 0)
                        {
                            <option value="" selected onselect="false">Please select Accomodation Type</option>
                        }
                        @foreach (var data in Model.AccomodationType)
                        {
                            var selected = data.ID == Model.AccomodationTypeID ? "selected" : string.Empty;
                            <option value="@data.ID" @selected>@data.Name</option>

                        }


                    </select>

                </div>
                
                <input type="hidden" value="@Model.ID" name="ID" /> 
                <div class="form-group">
                    <label for="Name">Name</label>
                    <input type="text" autocomplete="off" class="form-control" value="@Model.Name" name="Name" id="Name" placeholder="Enter Accomodation Package Name">
                </div>
                <div class="form-group">
                    <label for="NoOfRoom">No Of Room</label>
                    <input type="number" autocomplete="off" class="form-control" value="@Model.NoOfRoom" name="NoOfRoom" id="NoOfRoom" placeholder="Enter No Of Room">
                </div>
                <div class="form-group">
                    <label for="FeePerNight">Fee Per Night</label>
                    <input type="number" autocomplete="off" class="form-control" value="@Model.FeePerNight" name="FeePerNight" id="FeePerNight" placeholder="Enter Fee Per Night">
                </div>
                <div class="form-group">
                    <label for="exampleFormControlFile1">Pictures</label>
                    <input id="selectFile" type="file" class="form-control-file"  multiple>
                </div>
                <div class="form-group" id="pictureArea">
                    @if (Model.AccomodationPackagePictures != null && Model.AccomodationPackagePictures.Count > 0)
                    {
                        foreach (var picture in Model.AccomodationPackagePictures)
                        {
                            <img src="/Content/images/AccomodationPackage/@picture.Picture.URL" class="img-fluid img-thumbnail" style="width:200px; height:200px; cursor:pointer; border:1px solid black" onclick="removeMe(this)" data-id="@picture.PictuerID"/>
                        }
                    }
                    <input type="hidden" id="pictueIDs" name="PictureIDs" />
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-success" data-dismiss="modal"><i class="fas fa-times"></i> Close</button>
            <button type="button" class="btn btn-danger" id="btnSave"><i class="fas fa-save"></i> Save</button>
        </div>
    </div>
}
<div id="imageTemplate">
    <img src=""  class="img-fluid" style="width:200px;" onclick="removeMe(this)"/>
</div>


<script>
    //Initialize Select2 Elements
    $('.select2').select2()
    $("#btnSave").on('click', function () {
        var imageIDs = [];
        $("#pictureArea img").each(function () {
            var imageID = $(this).attr("data-id");
            imageIDs.push(imageID);
        });
        $("#pictueIDs").val(imageIDs.join());
        $.ajax({
            method: 'post',
            url: '@Url.Action("Action","AccomodationPackages")',
            data: $("#accomodationPacakgeForm").serialize()
        }).done(function (response) {
            if (response.Success) {
                $('#myModal').modal('toggle');
                Swal.fire({
                    position: 'top-end',
                    icon: 'success',
                    title: response.Message,
                    showConfirmButton: false,
                    timer: 1500
                })
                window.setTimeout(function () {
                    window.location.reload();
                }, 1500)
            }
            else {
                Swal.fire({
                    position: 'top-end',
                    icon: 'warning',
                    title: response.Message,
                    showConfirmButton: true,

                })
            }

        })

    })

    $("#selectFile").on("change", function () {
        var pictures = this.files;
        var formData = new FormData();
        for (var i = 0; i < pictures.length; i++) {
            formData.append("Picture ",pictures[i]);
        }
        $.ajax({
            method:'Post',
            url: '@Url.Action("UploadPicture", "Shared")',
            data: formData,
            dataType: 'json',
            processData: false,
            contentType:false
        }).done(function (response) {
            for (var i = 0; i < response.pictuerJSON.length; i++) {
                var picture = response.pictuerJSON[i];
                var $imgHTML = $("#imageTemplate").clone();
                $imgHTML.find('img').attr('src', '/Content/images/AccomodationPackage/' + picture.URL).addClass('img-thumbnail').css({ 'cursor': 'pointer', 'height': 200, 'border': '1px solid black' });
                $imgHTML.find('img').attr('data-id',picture.ID );
                $("#pictureArea").append($imgHTML.html());
            }

        }).fail(function (xhr, status, error) {
            alert("Some error");
            console.log(error);
        })

    })
    function removeMe(element) {
        element.remove();
    }
</script>

HMS.Web/Areas/Dashboard/Views/AccomodationPackages/_Listing.cshtml
@model HMS.Web.Areas.Dashboard.ViewModels.AccomodationPackagesListingModel
@{var row = 0; }
<div class="card">
    <div class="card-header">
        <div class="row mb-2">
            <div class="col-sm-12">
                <h3 class="m-0 text-dark">Accomodation Packages</h3>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="input-group">
            <select id="pageSize">
                <option value="10">10</option>
                <option value="20">20</option>
                <option value="30">30</option>
                <option value="50">50</option>
                <option value="100">100</option>
            </select>
            <input type="text" class="form-control" placeholder="search by Accomodation Type Name" aria-label="Accomodation Type Name" aria-describedby="basic-addon2" id="searchText" value="@Model.SearchTerm" autocomplete="off">
            <div class="input-group-append">
                <button data-href="@Url.Action("Listing", "AccomodationPackages")" id="btnSearch" class="btn btn-outline-warning btn-sm" type="button"><i class="fa fa-search"></i></button>
                <button data-href="@Url.Action("Listing", "AccomodationPackages")" id="btnReset" class="btn btn-outline-primary btn-sm btn-sm" type="button"><i class="fas fa-sync"></i></button>
                <button data-href="@Url.Action("Action", "AccomodationPackages")" class="data-btn btn btn-outline-success btn-sm btn-sm" type="button" data-toggle="modal" data-target="#myModal"><i class="fa fa-plus"></i></button>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div style="height: 300px; overflow: auto;">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th scope="col">#SL</th>
                        <th scope="col">Name</th>
                        <th scope="col">AccomodationType Name</th>
                        <th scope="col">No Of Room</th>
                        <th scope="col">Fee Per Night</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.AccomodationPackages != null && Model.AccomodationPackages.Count > 0)
            {
                foreach (var data in Model.AccomodationPackages)
                {
                    row = row + 1;
                            <tr>
                                <th scope="row">@row</th>
                                <td>@data.Name</td>
                                <td>@data.AccomodationType.Name</td>
                                <td>@data.NoOfRoom</td>
                                <td>@data.FeePerNight</td>
                                <td width="100">
                                    <button data-href="@Url.Action("Action", "AccomodationPackages", new { id = data.ID })" class="data-btn btn btn-success btn-sm"><i class="far fa-edit"></i></button>
                                    <button data-href="@Url.Action("Delete", "AccomodationPackages", new { id = data.ID })" class="delete-btn btn btn-danger btn-sm"><i class="fas fa-trash-alt"></i></button>
                                </td>
                            </tr>

                        }

                    }
                    else
                    {
                        <tr>
                            <td colspan="5">
                                <div class="alert alert-secondary" role="alert">
                                    Sorry! No record exist.
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer clearfix">
        <ul class="pagination pagination-sm m-0 float-right">
            @if (Model.Pager != null && Model.Pager.TotalItems > 10)
            {
                if (Model.Pager.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link datalink" style="cursor:pointer" data-href="@Url.Action("Listing", "AccomodationPackages", new { pageNo = Model.Pager.CurrentPage - 1, pageSize = Model.PageSize })" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                }
                for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                {
                    var activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;
                    <li class="page-item @activeClass"><a class="page-link datalink" style="cursor:pointer" href="#" data-href="@Url.Action("Listing","AccomodationPackages",new {pageNo = page, pageSize = Model.PageSize })">@page</a></li>
                }
                if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link datalink" style="cursor:pointer" data-href="@Url.Action("Listing", "AccomodationPackages", new { pageNo = Model.Pager.CurrentPage + 1, pageSize = Model.PageSize })" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                }
            }
        </ul>
    </div>
</div>


<script>
    $(".data-btn").on('click', function () {
        $.ajax({
            method: 'Get',
            url: $(this).attr('data-href')
        }).done(function (response) {
            $('#myModal').modal('toggle');
            $("#myModal .modal-dialog").html(response);
        })
    })
    $(".delete-btn").on('click', function () {

        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    method: 'Get',
                    url: $(this).attr('data-href')
                }).done(function (response) {
                        if (response.Success) {
                        Swal.fire(
                        'Deleted!',
                        response.Message,
                        'success'
                        )
                        window.setTimeout(function () {
                            window.location.reload();
                        }, 1500)}
                        else {
                        Swal.fire(
                        'Deleted!',
                        response.Message,
                        'warning'
                        )}
                })
            }
        })
    })
    $("#btnSearch").click(function () {
        var searchText = $("#searchText").val();
        $.ajax({
            method: 'Get',
            url: $(this).attr('data-href'),
            data: { searchTearm: searchText, pageNo:'@Model.PageNo', pageSize:'@Model.PageSize' }
        }).done(function (response) {
            $("#listData").html(response);
            $("#pageSize option[selected]").removeAttr("selected");
            $("#pageSize option[value=" + @Model.PageSize + "]").attr("selected","selected");
        }).fail(function (xhr, ajaxOptions, thrownError) {
            alert(xhr.status);
            console.log(thrownError);
        })
    })
    $("#btnReset").click(function () {
        var searchText = $("#searchText").val();
        $.ajax({
            method: 'Get',
            url: $(this).attr('data-href')
        }).done(function (response) {
            $("#listData").html(response);
        }).fail(function (xhr, ajaxOptions, thrownError) {
            alert(xhr.status);
            console.log(thrownError);
        })
    })

    $("#pageSize").change(function () {
        var searchText = $("#searchText").val();
        var pageSize = $("#pageSize").val();
        $.ajax({
            method: 'Get',
            url: '@Url.Action("Listing", "AccomodationPackages")',
            data: { searchTearm: searchText, pageSize: pageSize }
        }).done(function (response) {
            $("#listData").html(response);
            $("#pageSize option[selected]").removeAttr("selected");
            $("#pageSize option[value=" + pageSize + "]").attr("selected","selected");
        }).fail(function (xhr, ajaxOptions, thrownError) {
            alert(xhr.status);
            console.log(thrownError);
        })
    })
     

    $(".datalink").click(function () {
        $.ajax({
            method: 'Get',
            url: $(this).attr('data-href'),
        }).done(function (response) {
            $("#listData").html(response);
        }).fail(function (xhr, ajaxOptions, thrownError) {
            alert(xhr.status);
            console.log(thrownError);
        })
    })
</script>