HMS.Web/Areas/Dashboard/Controllers/AccomodationController.cs
using HMS.Entities;
using HMS.Services;
using HMS.Web.Areas.Dashboard.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HMS.Web.Areas.Dashboard.Controllers
{
    public class AccomodationController : Controller
    {
        private AccomodationService _AccomodationService;
        private Accomodation _Accomodation;
        private AccomodationPackagesService _AccomodationPackagesService;
        private SharedService _SharedService;
        private Picture _Picture;
        public AccomodationController()
        {
            _AccomodationPackagesService = new AccomodationPackagesService();
            _AccomodationService = new AccomodationService();
            _Accomodation = new Accomodation();
            _Picture = new Picture();
            _SharedService = new SharedService();
        }
        // GET: Dashboard/AccomodationType
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult Listing(string searchTearm,int? accomodationPackageId, int? pageNo, int? pageSize)
        {
            AccomodationListingModel model = new AccomodationListingModel();
            pageNo = pageNo ?? 1;
            pageSize = pageSize ?? 10;
            model.Accomodations = _AccomodationService.GetAllAccomodation(searchTearm, accomodationPackageId, pageNo.Value, pageSize.Value);
            model.AccomodatioPackages = _AccomodationPackagesService.GetAllAccomodationPackage();
            int totalItems = _AccomodationService.TotalItemCount(searchTearm, accomodationPackageId);
            model.Pager = new Pager(totalItems, pageNo, pageSize.Value);
            model.SearchTerm = searchTearm;
            model.PageNo = pageNo.Value;
            model.PageSize = pageSize.Value;
            return PartialView("_Listing", model);
        }
        [HttpGet]
        public PartialViewResult Action(int? id)
        {
            AccomodationModel model = new AccomodationModel();
            if (id.HasValue)
            {
                _Accomodation = _AccomodationService.GetAccomodationById(id.Value);
                model.ID = _Accomodation.ID;
                model.Name = _Accomodation.Name;
                model.AccomodationPackageID = _Accomodation.AccomodationPackageID;
                model.Description = _Accomodation.Description;
                model.AccomodationPictures = _Accomodation.AccomodationPictures;
            }
            model.AccomodationPackage = _AccomodationPackagesService.GetAllAccomodationPackage();

            return PartialView("_Action", model);
        }
        [HttpPost]
        public JsonResult Action(AccomodationModel model)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            var message = "";
            bool data = false;
            try
            {
                if (ModelState.IsValid)
                {
                    List<int> picturesIDs = model.PictureIDs.Split(',').Select(x => int.Parse(x)).ToList();
                    var pictures = _SharedService.GetPicturesByIDs(picturesIDs);
                    if (model.ID > 0)
                    {
                        _Accomodation = _AccomodationService.GetAccomodationById(model.ID);
                        _Accomodation.Name = model.Name;
                        _Accomodation.Description = model.Description;
                        _Accomodation.AccomodationPackageID = model.AccomodationPackageID;
                        _Accomodation.AccomodationPictures.Clear();
                        _Accomodation.AccomodationPictures.AddRange(pictures.Select(x => new AccomodationPictures() { PictuerID = x.ID, AccomodationID = model.ID }));            
                        data = _AccomodationService.UpdateAccomodation(_Accomodation);
                    }
                    else
                    {
                        _Accomodation.AccomodationPictures = new List<AccomodationPictures>();
                        _Accomodation.AccomodationPictures.AddRange(pictures.Select(x => new AccomodationPictures() { PictuerID = x.ID }));
                        _Accomodation.ID = model.ID;
                        _Accomodation.Name = model.Name;
                        _Accomodation.Description = model.Description;
                        _Accomodation.AccomodationPackageID = model.AccomodationPackageID;
                        data = _AccomodationService.SaveAccomodation(_Accomodation);
                    }

                }
                else
                {
                    message = "Please enter valid data!!";

                }

            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            if (data)
            {
                message = "Data Save Successfully!!";
                result.Data = new { Success = true, Message = message };
            }
            else
            {
                result.Data = new { Success = false, Message = message };
            }
            return result;

        }

        public JsonResult Delete(int id)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            dynamic message = "";
            var data = false;
            try
            {
                if (id > 0)
                {
                    _Accomodation = _AccomodationService.GetAccomodationById(id);
                    data = _AccomodationService.DeleteAccomodation(_Accomodation);
                }
                else
                {
                    message = "Please click valid item";
                }
            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            if (data)
            {
                message = "Data Delete Successfully !!";
                result.Data = new { Success = true, Message = message };
            }
            else
            {
                result.Data = new { Success = false, Message = message };
            }

            return result;
        }

    }
}

HMS.Web/Areas/Dashboard/Controllers/AccomodationTypeController.cs
using HMS.Entities;
using HMS.Services;
using HMS.Web.Areas.Dashboard.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HMS.Web.Areas.Dashboard.Controllers
{
    public class AccomodationTypeController : Controller
    {
        private AccomodationTypeService _AccomodationTypeService;
        private AccomodationType _AccomodationType;
        public AccomodationTypeController()
        {
           _AccomodationTypeService = new AccomodationTypeService();
            _AccomodationType = new AccomodationType();
        }
        // GET: Dashboard/AccomodationType
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult Listing(string searchTearm, int? pageNo, int? pageSize)
        {
            AccomodationTypeListingModel model = new AccomodationTypeListingModel();
            pageNo = pageNo ?? 1;
            pageSize = pageSize ?? 10;
            model.AccomodationTypes = _AccomodationTypeService.GetAllAccomodationType(searchTearm, pageNo.Value, pageSize.Value);
            int totalItems = _AccomodationTypeService.TotalItemCount(searchTearm);
            model.Pager = new Pager(totalItems, pageNo, pageSize.Value);
            model.SearchTerm = searchTearm;
            model.PageNo = pageNo.Value;
            model.PageSize = pageSize.Value;
            return PartialView("_Listing",model);
        }
        [HttpGet]
        public PartialViewResult Action(int? id)
        {
            AccomodationTypeModel model = new AccomodationTypeModel();
            if (id.HasValue)
            {
                _AccomodationType = _AccomodationTypeService.GetAccomodationById(id.Value);
                model.ID = _AccomodationType.ID;
                model.Name = _AccomodationType.Name;
                model.Description = _AccomodationType.Description;
            }

            return PartialView("_Action",model);
        }
        [HttpPost]
        public JsonResult Action(AccomodationTypeModel model)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            var message = "";
            bool data = false;
            try
            {
                if (ModelState.IsValid)
                {
                    if (model.ID > 0)
                    {
                        _AccomodationType = _AccomodationTypeService.GetAccomodationById(model.ID);
                        _AccomodationType.Name = model.Name;
                        _AccomodationType.Description = model.Description;
                        data = _AccomodationTypeService.UpdateAccomodationType(_AccomodationType);
                    }
                    else
                    {
                        _AccomodationType.ID = model.ID;
                        _AccomodationType.Name = model.Name;
                        _AccomodationType.Description = model.Description;
                        data = _AccomodationTypeService.SaveAccomodationType(_AccomodationType);
                    }
                   
                }
                else
                {
                    message = "Please enter valid data!!";
                   
                }
                         
            }
            catch(Exception ex)
            {
                message = ex.Message;
            }
            if (data)
            { 
                message = "Data Save Successfully!!";
                result.Data = new { Success = true, Message = message };
            }                
            else
            {
                result.Data = new { Success = false, Message = message };
            }
            return result;

        }

        public JsonResult Delete(int id)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            dynamic message = "";
            var data = false;
            try
            {
                if (id > 0)
                {
                    _AccomodationType = _AccomodationTypeService.GetAccomodationById(id);
                     data = _AccomodationTypeService.DeleteAccomodationType(_AccomodationType);
                }
                else
                {
                    message = "Please click valid item";
                }
            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            if (data)
            {
                message = "Data Delete Successfully !!";
                result.Data = new { Success = true, Message = message };
            }
            else
            {
                result.Data = new { Success = false, Message = message };
            }

            return result;
        }

    }
}

HMS.Web/Areas/Dashboard/Controllers/RolesController.cs
using HMS.Entities;
using HMS.Services;
using HMS.Web.Areas.Dashboard.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace HMS.Web.Areas.Dashboard.Controllers
{
    public class RolesController : Controller
    {
        private HMSSignInManagerService _signInManager;
        private HMSUserManagerService _userManager;
        private HMSRolesManagerService _roleManager;

        public RolesController()
        {
        }

        public RolesController(HMSUserManagerService userManager, HMSSignInManagerService signInManager, HMSRolesManagerService roleManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
            RoleManager = roleManager;
        }

        public HMSSignInManagerService SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<HMSSignInManagerService>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public HMSUserManagerService UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<HMSUserManagerService>();
            }
            private set
            {
                _userManager = value;
            }
        }
        public HMSRolesManagerService RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().GetUserManager<HMSRolesManagerService>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        // GET: Dashboard/Users
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult Listing(string searchTearm, int? pageNo, int? pageSize)
        {
            RolesListingModel model = new RolesListingModel();
            pageNo = pageNo ?? 1;
            pageSize = pageSize ?? 10;
            model.Roles = SearchRoles(searchTearm,  pageNo, pageSize.Value);
            int totalItems = SearchRolesCount(searchTearm);
            model.Pager = new Pager(totalItems, pageNo, pageSize.Value);
            model.SearchTerm = searchTearm;
            model.PageNo = pageNo.Value;
            model.PageSize = pageSize.Value;
            return PartialView("_Listing", model);
        }
        [HttpGet]
        public async Task<PartialViewResult> Action(string id)
        {
            RolesModel model = new RolesModel();
            if (!string.IsNullOrEmpty(id))
            {
                var role = await RoleManager.FindByIdAsync(id);
                model.ID = role.Id;
                model.Name = role.Name;


            }
            return PartialView("_Action", model);
        }
        [HttpPost]
        public async Task<JsonResult> Action(RolesModel model)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            var message = "";
            IdentityResult data = null;
            try
            {
                if (ModelState.IsValid)
                {
                    if (!string.IsNullOrEmpty(model.ID))
                    {
                        var role = await RoleManager.FindByIdAsync(model.ID);
                        role.Name = model.Name;
                        data = await RoleManager.UpdateAsync(role);
                    }
                    else
                    {
                        var role = new IdentityRole();
                        role.Name = model.Name;
                      
                        data = await RoleManager.CreateAsync(role);
                    }

                }
                else
                {
                    message = "Please enter valid users!!";

                }

            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            if (data.Succeeded)
            {
                message = "Role Save Successfully!!";
                result.Data = new { Success = true, Message = message };
            }
            else
            {
                result.Data = new { Success = false, Message = string.Join(",", data.Errors) };
            }
            return result;

        }

        public async Task<JsonResult> Delete(string id)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            dynamic message = "";
            IdentityResult data = null;
            try
            {
                if (!string.IsNullOrEmpty(id))
                {
                    var role = await RoleManager.FindByIdAsync(id);
                    data = await RoleManager.DeleteAsync(role);
                }
                else
                {
                    message = "Role is not valid";
                }
            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            if (data.Succeeded)
            {
                message = "User Delete Successfully!!";
                result.Data = new { Success = true, Message = message };
            }
            else
            {
                result.Data = new { Success = false, Message = string.Join(",", data.Errors) };
            }

            return result;
        }


        public List<IdentityRole> SearchRoles(string searchTearm,  int? pageNo, int pageSize)
        {
            var roles = RoleManager.Roles.AsQueryable();
            if (string.IsNullOrEmpty(searchTearm) == false)
            {
                roles = roles.Where(x => x.Name.ToLower().Contains(searchTearm.ToLower()) || x.Id.ToLower().Contains(searchTearm.ToLower()));
            }
            return roles.OrderByDescending(x => x.Name).Skip((pageNo.Value - 1) * pageSize).Take(pageSize).ToList();
        }
        public int SearchRolesCount(string searchTearm)
        {
            var roles = RoleManager.Roles.AsQueryable();
            if (string.IsNullOrEmpty(searchTearm) == false)
            {
                roles = roles.Where(x => x.Name.ToLower().Contains(searchTearm.ToLower()));
            }
            return roles.Count();
        }
    }
}

HMS.Web/Areas/Dashboard/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <strong>Copyright &copy; @DateTime.Today.Year.ToString() <a href="#">AdminLTE.io</a>.</strong>
    All rights reserved.

</footer>
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->

HMS.Web/Areas/Dashboard/Views/Shared/_JsFile.cshtml
<!-- jQuery UI 1.11.4 -->
<script src="~/Areas/Dashboard/Content/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>

<!-- ChartJS -->
<script src="~/Areas/Dashboard/Content/plugins/chart.js/Chart.min.js"></script>
<!-- Sparkline -->
<script src="~/Areas/Dashboard/Content/plugins/sparklines/sparkline.js"></script>
<!-- JQVMap -->
<script src="~/Areas/Dashboard/Content/plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="~/Areas/Dashboard/Content/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="~/Areas/Dashboard/Content/plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="~/Areas/Dashboard/Content/plugins/moment/moment.min.js"></script>
<script src="~/Areas/Dashboard/Content/plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="~/Areas/Dashboard/Content/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="~/Areas/Dashboard/Content/plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="~/Areas/Dashboard/Content/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="~/Areas/Dashboard/Content/dist/js/adminlte.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="~/Areas/Dashboard/Content/dist/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="~/Areas/Dashboard/Content/dist/js/demo.js"></script>
<!--Sweetalert add-->
<script src="~/Areas/Dashboard/Content/plugins/sweetalert2/sweetalert2.min.js"></script>

HMS.Web/Areas/Dashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Areas/Dashboard/Content/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="~/Areas/Dashboard/Content/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Areas/Dashboard/Content/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/Areas/Dashboard/Content/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Areas/Dashboard/Content/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/Areas/Dashboard/Content/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/Areas/Dashboard/Content/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/Areas/Dashboard/Content/plugins/summernote/summernote-bs4.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- jQuery -->

    <link href="~/Areas/Dashboard/Content/plugins/select2/css/select2.min.css" rel="stylesheet" />

  
    <script src="~/Areas/Dashboard/Content/plugins/jquery/jquery.min.js"></script>
    <script src="~/Areas/Dashboard/Content/plugins/select2/js/select2.full.min.js"></script>
 
    <!-- Bootstrap 4 -->
    <script src="~/Areas/Dashboard/Content/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <link href="~/Areas/Dashboard/Content/plugins/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <script>
  
    </script>
    <div class="wrapper">
       @Html.Partial("_Navbar")
        @Html.Partial("_Sidebar")
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
         
            <!-- Main content -->
            <section class="content">
                
                <div class="container-fluid">
                    @RenderBody()
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
      @Html.Partial("_Footer")
   </div>
    @Html.Partial("_JsFile")
   
</body>
</html>

HMS.Web/Areas/Dashboard/Views/Shared/_Sidebar.cshtml
  <!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <img src="~/Areas/Dashboard/Content/dist/img/credit/logo.png" alt="Hotel Management" class="brand-image img-circle elevation-3"
             style="opacity: .8" />
        <span class="brand-text font-weight-light">Hotel Management</span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/Areas/Dashboard/Content/dist/img/45887176_2039127959482269_5993646807396122624_n.jpg" class="img-circle elevation-2" alt="User Image" />
            </div>
            <div class="info">
                <a href="#" class="d-block">Md Somrat Akbor</a>
            </div>
        </div>
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                <li class="nav-item">
                    <a href="@Url.Action("Index","Dashboard")" class="nav-link">
                        <i class="fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index","AccomodationType")" class="nav-link">
                        <i class="fas fa-hotel"></i>
                        <p>
                            Accomodation Type
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index","AccomodationPackages")" class="nav-link">
                        <i class="fas fa-cubes"></i>
                        <p>
                            Accomodation Packages
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index","Accomodation")" class="nav-link">
                        <i class="fas fa-person-booth"></i>
                        <p>
                            Accomodation
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index","Users")" class="nav-link">
                        <i class="fas fa-users"></i>
                        <p>
                            Users
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index","Roles")" class="nav-link">
                        <i class="fas fa-users-cog"></i>
                        <p>
                            Roles
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>