HMS.Web/Areas/Dashboard/Controllers/AccomodationController.cs
using HMS.Entities;
using HMS.Services;
using HMS.Web.Areas.Dashboard.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HMS.Web.Areas.Dashboard.Controllers
{
    public class AccomodationController : Controller
    {
        private AccomodationService _AccomodationService;
        private Accomodation _Accomodation;
        private AccomodationPackagesService _AccomodationPackagesService;
        private SharedService _SharedService;
        private Picture _Picture;
        public AccomodationController()
        {
            _AccomodationPackagesService = new AccomodationPackagesService();
            _AccomodationService = new AccomodationService();
            _Accomodation = new Accomodation();
            _Picture = new Picture();
            _SharedService = new SharedService();
        }
        // GET: Dashboard/AccomodationType
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult Listing(string searchTearm,int? accomodationPackageId, int? pageNo, int? pageSize)
        {
            AccomodationListingModel model = new AccomodationListingModel();
            pageNo = pageNo ?? 1;
            pageSize = pageSize ?? 10;
            model.Accomodations = _AccomodationService.GetAllAccomodation(searchTearm, accomodationPackageId, pageNo.Value, pageSize.Value);
            model.AccomodatioPackages = _AccomodationPackagesService.GetAllAccomodationPackage();
            int totalItems = _AccomodationService.TotalItemCount(searchTearm, accomodationPackageId);
            model.Pager = new Pager(totalItems, pageNo, pageSize.Value);
            model.SearchTerm = searchTearm;
            model.PageNo = pageNo.Value;
            model.PageSize = pageSize.Value;
            return PartialView("_Listing", model);
        }
        [HttpGet]
        public PartialViewResult Action(int? id)
        {
            AccomodationModel model = new AccomodationModel();
            if (id.HasValue)
            {
                _Accomodation = _AccomodationService.GetAccomodationById(id.Value);
                model.ID = _Accomodation.ID;
                model.Name = _Accomodation.Name;
                model.AccomodationPackageID = _Accomodation.AccomodationPackageID;
                model.Description = _Accomodation.Description;
                model.AccomodationPictures = _Accomodation.AccomodationPictures;
            }
            model.AccomodationPackage = _AccomodationPackagesService.GetAllAccomodationPackage();

            return PartialView("_Action", model);
        }
        [HttpPost]
        public JsonResult Action(AccomodationModel model)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            var message = "";
            bool data = false;
            try
            {
                if (ModelState.IsValid)
                {
                    List<int> picturesIDs = model.PictureIDs.Split(',').Select(x => int.Parse(x)).ToList();
                    var pictures = _SharedService.GetPicturesByIDs(picturesIDs);
                    if (model.ID > 0)
                    {
                        _Accomodation = _AccomodationService.GetAccomodationById(model.ID);
                        _Accomodation.Name = model.Name;
                        _Accomodation.Description = model.Description;
                        _Accomodation.AccomodationPackageID = model.AccomodationPackageID;
                        _Accomodation.AccomodationPictures.Clear();
                        _Accomodation.AccomodationPictures.AddRange(pictures.Select(x => new AccomodationPictures() { PictuerID = x.ID, AccomodationID = model.ID }));            
                        data = _AccomodationService.UpdateAccomodation(_Accomodation);
                    }
                    else
                    {
                        _Accomodation.AccomodationPictures = new List<AccomodationPictures>();
                        _Accomodation.AccomodationPictures.AddRange(pictures.Select(x => new AccomodationPictures() { PictuerID = x.ID }));
                        _Accomodation.ID = model.ID;
                        _Accomodation.Name = model.Name;
                        _Accomodation.Description = model.Description;
                        _Accomodation.AccomodationPackageID = model.AccomodationPackageID;
                        data = _AccomodationService.SaveAccomodation(_Accomodation);
                    }

                }
                else
                {
                    message = "Please enter valid data!!";

                }

            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            if (data)
            {
                message = "Data Save Successfully!!";
                result.Data = new { Success = true, Message = message };
            }
            else
            {
                result.Data = new { Success = false, Message = message };
            }
            return result;

        }

        public JsonResult Delete(int id)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            dynamic message = "";
            var data = false;
            try
            {
                if (id > 0)
                {
                    _Accomodation = _AccomodationService.GetAccomodationById(id);
                    data = _AccomodationService.DeleteAccomodation(_Accomodation);
                }
                else
                {
                    message = "Please click valid item";
                }
            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            if (data)
            {
                message = "Data Delete Successfully !!";
                result.Data = new { Success = true, Message = message };
            }
            else
            {
                result.Data = new { Success = false, Message = message };
            }

            return result;
        }

    }
}

HMS.Web/Areas/Dashboard/Controllers/SharedController.cs
using HMS.Entities;
using HMS.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HMS.Web.Areas.Dashboard.Controllers
{
    public class SharedController : Controller
    {
        private SharedService _SharedService;

        public SharedController()
        {
            _SharedService = new SharedService();

        }
        // GET: Dashboard/Shared
        public ActionResult Index()
        {
            return View();
        }

     


        
        public JsonResult UploadPicture()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            var files = Request.Files;
            List<object> pictuerJSON = new List<object>();
            try
            {
                for (int i = 0; i < files.Count; i++)
                {
                    var picture = files[i];
                    var fileName = Guid.NewGuid() + Path.GetExtension(picture.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/images/AccomodationPackage/"), fileName);
                    picture.SaveAs(path);
                    var dbPictuer = new Picture();
                    dbPictuer.URL = fileName;
                    int pictureID = _SharedService.SavePicture(dbPictuer);
                    pictuerJSON.Add(new { ID = pictureID, URL = dbPictuer.URL });

                }
                result.Data = new { Success = true, pictuerJSON };
            }
            
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }
            return result;
        }
    }
}

HMS.Web/Areas/Dashboard/Views/Accomodation/Index.cshtml
<div id="listData">
    @{Html.RenderAction("Listing");}
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
    </div>
</div>

HMS.Web/Areas/Dashboard/Views/Accomodation/_Action.cshtml
@model HMS.Web.Areas.Dashboard.ViewModels.AccomodationModel
@if (Model != null)
{
    <div class="modal-content">
        <div class="modal-header  bg-gradient-gray-dark">
            @if (Model.ID > 0)
                {
                <h5 class="modal-title" id="exampleModalLabel">Edit Accomodation</h5>
            }
            else
            {
                <h5 class="modal-title" id="exampleModalLabel">Create Accomodation</h5>
            }

            <button type="button" class="close btn btn-warning btn-sm" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="accomodationForm">
                <div class="form-group">
                    <label for="Name">Name</label>
                    <select name="AccomodationPackageID" class="form-control select2 select2-danger" data-dropdown-css-class="select2-danger" style="width: 100%;">

                        @if (Model.AccomodationPackageID <= 0)
                        {
                            <option value="" selected onselect="false">Please select Accomodation Packages</option>
                        }
                        @foreach (var data in Model.AccomodationPackage)
                        {
                            var selected = data.ID == Model.AccomodationPackageID ? "selected" : string.Empty;
                            <option value="@data.ID" @selected>@data.Name</option>

                        }


                    </select>

                </div>

                <input type="hidden" value="@Model.ID" name="ID" />
                <div class="form-group">
                    <label for="Name">Name</label>
                    <input type="text" autocomplete="off" class="form-control" value="@Model.Name" name="Name" id="Name" placeholder="Enter Accomodation Package Name">
                </div>
                <div class="form-group">
                    <label for="Description">Description</label>
                    <textarea class="form-control" id="Description" name="Description" rows="3" placeholder="Enter Accomodation Description">@Model.Description</textarea>
                </div>
                <div class="form-group">
                    <label for="exampleFormControlFile1">Pictures</label>
                    <input id="selectFile" type="file" class="form-control-file" multiple>
                </div>
                <div class="form-group" id="pictureArea">
                    @if (Model.AccomodationPictures != null && Model.AccomodationPictures.Count > 0)
                    {
                        foreach (var picture in Model.AccomodationPictures)
                        {
                            <img src="/Content/images/AccomodationPackage/@picture.Picture.URL" class="img-fluid img-thumbnail" style="width:200px; height:200px; cursor:pointer; border:1px solid black" onclick="removeMe(this)" data-id="@picture.PictuerID" />
                        }
                    }
                    <input type="hidden" id="pictueIDs" name="PictureIDs" />
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-success" data-dismiss="modal"><i class="fas fa-times"></i> Close</button>
            <button type="button" class="btn btn-danger" id="btnSave"><i class="fas fa-save"></i> Save</button>
        </div>
    </div>
}
<div id="imageTemplate">
    <img src="" class="img-fluid" style="width:200px;" onclick="removeMe(this)" />
</div>


<script>
    //Initialize Select2 Elements
    $('.select2').select2()
    $("#btnSave").on('click', function () {
        var imageIDs = [];
        $("#pictureArea img").each(function () {
            var imageID = $(this).attr("data-id");
            imageIDs.push(imageID);
        });
        $("#pictueIDs").val(imageIDs.join());
        $.ajax({
            method: 'post',
            url: '@Url.Action("Action","Accomodation")',
            data: $("#accomodationForm").serialize()
        }).done(function (response) {
            if (response.Success) {
                $('#myModal').modal('toggle');
                Swal.fire({
                    position: 'top-end',
                    icon: 'success',
                    title: response.Message,
                    showConfirmButton: false,
                    timer: 1500
                })
                window.setTimeout(function () {
                    window.location.reload();
                }, 1500)
            }
            else {
                Swal.fire({
                    position: 'top-end',
                    icon: 'warning',
                    title: response.Message,
                    showConfirmButton: true,

                })
            }

        })

    })
    $("#selectFile").on("change", function () {
        var pictures = this.files;
        var formData = new FormData();
        for (var i = 0; i < pictures.length; i++) {
            formData.append("Picture ", pictures[i]);
        }
        $.ajax({
            method: 'Post',
            url: '@Url.Action("UploadPicture", "Shared")',
            data: formData,
            dataType: 'json',
            processData: false,
            contentType: false
        }).done(function (response) {
            for (var i = 0; i < response.pictuerJSON.length; i++) {
                var picture = response.pictuerJSON[i];
                var $imgHTML = $("#imageTemplate").clone();
                $imgHTML.find('img').attr('src', '/Content/images/AccomodationPackage/' + picture.URL).addClass('img-thumbnail').css({ 'cursor': 'pointer', 'height': 200, 'border': '1px solid black' });
                $imgHTML.find('img').attr('data-id', picture.ID);
                $("#pictureArea").append($imgHTML.html());
            }

        }).fail(function (xhr, status, error) {
            alert("Some error");
            console.log(error);
        })

    })
    function removeMe(element) {
        element.remove();
    }
</script>